apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ars-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: develop
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: git@github.com:Helium-Health/ARS.git
    targetRevision: develop
    ref: values
  - repoURL: git@gitlab.com:heliumemr/Helium-Helm-Chart.git
    targetRevision: main
    path: ./
    helm:
      valueFiles:
        - $values/argocd_manifests/dev/values/ars.yaml          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true